// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAofrRaieSNIcjoOlrwscNKHsw3qrXqoJ0',
    appId: '1:1026041146477:web:b3dab678db7c55e720e364',
    messagingSenderId: '1026041146477',
    projectId: 'fluutter-task-mostafa',
    authDomain: 'fluutter-task-mostafa.firebaseapp.com',
    storageBucket: 'fluutter-task-mostafa.firebasestorage.app',
    measurementId: 'G-ZEQXKGCCWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0uUHxIoeCAET9Um3Yu2n-yWIMTpL0qV4',
    appId: '1:1026041146477:android:2ad882ee5f8e028620e364',
    messagingSenderId: '1026041146477',
    projectId: 'fluutter-task-mostafa',
    storageBucket: 'fluutter-task-mostafa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALXNLz1lHMibjcXIWK6ZfdYLgETbzcDEY',
    appId: '1:1026041146477:ios:2cc402c538c5754420e364',
    messagingSenderId: '1026041146477',
    projectId: 'fluutter-task-mostafa',
    storageBucket: 'fluutter-task-mostafa.firebasestorage.app',
    iosBundleId: 'com.example.flutterTasksMostafa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALXNLz1lHMibjcXIWK6ZfdYLgETbzcDEY',
    appId: '1:1026041146477:ios:2cc402c538c5754420e364',
    messagingSenderId: '1026041146477',
    projectId: 'fluutter-task-mostafa',
    storageBucket: 'fluutter-task-mostafa.firebasestorage.app',
    iosBundleId: 'com.example.flutterTasksMostafa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAofrRaieSNIcjoOlrwscNKHsw3qrXqoJ0',
    appId: '1:1026041146477:web:337587a3384c8e5d20e364',
    messagingSenderId: '1026041146477',
    projectId: 'fluutter-task-mostafa',
    authDomain: 'fluutter-task-mostafa.firebaseapp.com',
    storageBucket: 'fluutter-task-mostafa.firebasestorage.app',
    measurementId: 'G-N0GTGGBFDE',
  );
}
